### ISSUE TITLE
fn.apply is not a function(hooks.js)

### ISSUE THREAD

**Issue by s1m0nDevs** [nutboltu/storybook-addon-mock#141]
![image](https://user-images.githubusercontent.com/53870756/196864301-4b85fcf0-1dc3-4256-8c6d-f55997460f25.png)
I see this error after updating to the latest version 3.2.0 from 2.4.1(see the same error on 3.0.0)

**Comment by s1m0nDevs** [comment]
Ok, so a couple of issues I found when was trying to investigate that issue. 
First of all the weirdest specific bug was related to my own interceptors. For some reason, I can only use custom headers with `string` data, otherwise, that somehow conflicts with the current package. So I have to change it to string.
![image](https://user-images.githubusercontent.com/53870756/196939068-8d6b9585-812b-46d5-8982-80ae7973b293.png)

And the other issue was related to the `disabled` parameter at `mockAddonConfigs`. If we set it like at documentation example - it will throw an error. But if keep it false by default - looks good.
